export const ERROR_CODES = {
  // health
  LIVENESS: 'HEALTH_LIVENESS',
  READINESS: 'HEALTH_READINESS',

  // auth
  SIGN_IN_EMAIL: 'SIGN_IN_EMAIL',
  SIGN_UP_EMAIL: 'SIGN_UP_EMAIL',
  SIGN_IN_TELEGRAM: 'SIGN_IN_TELEGRAM',
  LOGOUT: 'LOGOUT',
  REFRESH_TOKEN: 'REFRESH_TOKEN',

  // users
  GET_USER: 'GET_USER',
  DELETE_USER: 'DELETE_USER',

  // monitor
  USER_MONITORS: 'USER_MONITORS',
  DETAILED_MONITOR: 'DETAILED_MONITOR',
  CREATE_MONITOR: 'CREATE_MONITOR',
  UPDATE_MONITOR: 'UPDATE_MONITOR',
  DELETE_MONITOR: 'DELETE_MONITOR',

  // analytics
  OVERVIEW_ANALYTICS: 'OVERVIEW_ANALYTICS',
  INCIDENTS_ANALYTICS: 'INCIDENTS_ANALYTICS',
  TIMELINE_ANALYTICS: 'TIMELINE_ANALYTICS',

  // notification
  LINK_TELEGRAM: 'LINK_TELEGRAM',
  UNLINK_TELEGRAM: 'UNLINK_TELEGRAM',
  TOGGLE_ALERT: 'TOGGLE_ALERT',
  GET_SETTINGS: 'GET_SETTINGS',

  // common
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  CONFLICT: 'CONFLICT',

  // system
  VALIDATION: 'VALIDATION',
  TIMEOUT: 'TIMEOUT',
  NETWORK: 'NETWORK',
  RATE_LIMIT: 'RATE_LIMIT',
  INTERNAL: 'INTERNAL',
  UNKNOWN: 'UNKNOWN',
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]
